# Generated by Django 4.1.5 on 2023-01-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
