# Generated by Django 4.1.5 on 2023-01-14 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_message_no_of_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeMessage',
        ),
    ]
